# Generated by Django 4.0.4 on 2022-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
